### ISSUE TITLE
[Bug]: Event Times in Mozilla Thunderbird Are Wrong with ICS file

### ISSUE THREAD

**Issue by propertunist** [add2cal/add-to-calendar-button#109]
### What happened?

I am a new user of your code and it's great, but I am having difficulty geting ICS exports to produce correct times in Mozilla Thunderbird calendars. The problem could well be one with Thunderbird itself (I'm using 91.11.0 (64-bit) on Linux Fedora 36).

I have tried exporting calendars with and without a timezone (plus passing in a UTC time or a time adjusted using moment.js to match the user's device timezone) but I am not able to produce an exported ICS file that produces events with correct start time in Thunderbird's calendar.

Sometimes the start time of my event is 10 hours out in Thunderbird, but renders ok in Google or the OS calendar. For example, this is the start time shown for the event in Thunderbird's calendar:
 
![image](https://user-images.githubusercontent.com/513903/182045562-17fdf81d-48ed-4ce8-92f1-22ff03b73694.png)

The difference between the UTC time and the local time is 10 hours, but I am in the GMT timezone so it shouldn't really be more than 1 hour different.

Is this a bug with Thunderbird or am i misconfiguring your plugin?

N.B. I also notice that Thunderbird creates a new calendar that it treats as a remote source for the imported item which is not ideal.

### How to reproduce?

1. Create a calendar event for add to calendar event using JS and attaching to a button using atcb_action.
2. Include either a local timezone, UTC or 'currentBrowser' as a timezone.
3. Save the resulting ICS file locally and open it in Mozilla Thunderbird via the 'open calendar' option.
4. Start time is incorrect.

### System & Environment

Dell Laptop - Fedora 36 (64 Bit)
Mozilla Firefox 102.0 (64-bit)
Mozilla Thunderbird 91.11.0 (64-bit)
v1.13.2 of add to calendar button

**Comment by jekuer** [comment]
Hi @propertunist ,
I will dig into it a little bit.
the ics times are all converted into UTC.
So, if your thunderbird shows something completely off, I would guess it has rather something to do with internal Timezone settings of your machine and/or thunderbird.
Can you check those settings (Timezone on fedora and Timezone in thunderbird) for me?
I could also imagine that thunderbird sets a Timezone for the ics itself, while setting it up as a remote calendar.

One next thing will be destinctive timezones in the ics file. If your timezones are correct, maybe that will fix the issue.

regarding the remote calendar: this is (afaik) not controlled by the ics but the calendar. Try not to "open calendar", but some other import way. Unfortunately, last time I used thunderbird was like 10 years ago. But I will investigate from my side as well.

**Comment by jekuer** [comment]
Hi @propertunist ,
I've tested it in different ways and could not really reproduce your observation.

1. Creating a new calender. This has nothing to do with the .ics file, but with the way you open it. Thunderbird asks you how you want to import it, if you go the import way. If you open the file via Thunderbird, it is even more simpler and goes into the calendar of your choice.
2. The time always adjusts to my timezone. Since the UTC time in your example is correct as well, I can say for sure that it has nothing to do with the ics file, but rather some strange timezone setup on your machine.
3. What I've said above still counts: With the upcoming improvements, the process might get more stable and maybe support you a little bit better. But with a big "maybe". Since the error is somehow on your machine, it is hard to debug whether any update to the script will optimize it for you (but to be fair, this would be the case for all kinds of ics generators).

If you find out more or new evidence on any misbehavior,  please add another comment, so I can re-open it. Thanks :)

**Comment by propertunist** [comment]
@jekuer Thanks for digging into this. I was about to tell you that the timezone on my PC is normal, but I didn't know there was a separate timezone set in Thunderbird. I checked it and it was set to Australia.. I was there last year but had no idea it was possible for this to happen! I'm pretty sure I didn't set it manually in Thunderbird, so I guess maybe it's a timezone bug with Thunderbird.
