### ISSUE TITLE
Provided time is not correct according to the timezone

### ISSUE THREAD

**Issue by mhasan-cmt** [add2cal/add-to-calendar-button#151]
Example:

`<div class="atcb" style="display:none;">
        {
          "name":"Reminder to star the add to calendar button repo",
          "description":"Check out the maybe easiest way to include add to calendar buttons to your website at:<br>→ [url]https://github.com/add2cal/add-to-calendar-button[/url]",
          "startDate":"2023-02-14",
          "endDate":"2023-02-14",
          "startTime":"00:00",
          "endTime":"23:30",
          "location":"World Wide Web",
          "options":[
            "Apple",
            "Google",
            "iCal",
            "Microsoft365",
            "MicrosoftTeams",
            "Outlook.com",
            "Yahoo"
          ],
          "timeZone":"America/Los_Angeles",
          "iCalFileName":"Reminder-Event"
        }
        </div>`

The result should show the start time 00:00 -> 1.00 and end time 23:30 -> 12:30 since I am in Asia/Dhaka Timezone.
![image](https://user-images.githubusercontent.com/54675198/187850868-7874db7e-1748-4dea-a8a4-e33866cad6c3.png)
but it is not.

**Comment by jekuer** [comment]
Hi @mhasan-cmt ,

Thanks for your comment.

The behavior you see is actually correct. Since the date is in February and the base time zone is Los Angeles, there is a DAYTIME change in between. In February, Los Angeles has a -8h offset (instead of the current -7h). Since Asia/Dhaka is always +6h, you see different spans bases on the month and day you are testing :).

Best,
Jens

**Comment by mhasan-cmt** [comment]
Hi @jekuer 
thanks for your answer, one more I need to know is, 
why is it showing different results for google calendar and ical
![Capture](https://user-images.githubusercontent.com/54675198/187978159-14217df5-9943-498b-9fbe-b93490a98ea9.PNG)

**Comment by jekuer** [comment]
@mhasan-cmt , can you please double-check that the timezone on your computer, outlook, and google calendar is the same? Mind that they are not synched by default, but have their own settings.
I have tested the code on my side and it works absolutely fine.

**Comment by mhasan-cmt** [comment]
both my google calendar timezone and computers time zone are like this
![computer timezone](https://user-images.githubusercontent.com/54675198/187985312-7195228e-59d5-4da0-8109-89371d9267fa.PNG)
![google cal](https://user-images.githubusercontent.com/54675198/187985316-ddbf579f-2abf-4f42-a7aa-5dbd1065ea29.PNG)

**Comment by jekuer** [comment]
Mhh. Strange.
The iCal is definitely right for your time zone.
Not sure why your Google is wrong - this even is the more stable one, since it always gets the same UTC string from the button and then adapts. Therefore, this needs to be some issue with your Google Calendar.
Even using your time zone on my side worked fine.

HOWEVER: On my side, I have no "Dhaka" option with Google, so I used the Bangladesh time. Maybe this is the bug on Google's side, not correctly supporting your specific time zone. You should try to contact them (even I am not sure if somebody will listen 😬 ).

Definitely no bug on the button's side.

**Comment by jekuer** [comment]
It sure is. However, impossible to solve from my end.
