### ISSUE TITLE
[Bug]: 1.16.0 does not load

### ISSUE THREAD

**Issue by houmark** [add2cal/add-to-calendar-button#203]
### What happened?

This may just be because we are using React, but browser check seems to have broken with the most recent version. Console shows:

> no further initialization due to wrong environment (no browser)

### How to reproduce?

We are running React and initialize like this:

```
const AddToCalendarButton = (props) => {
  const { event } = props || {};
  useEffect(ATCBInit, []);

  if (!event) return null;

  return <div className="atcb">{JSON.stringify(event)}</div>;
};
```

### Screenshots & more

![CleanShot 2022-10-01 at 18 31 13](https://user-images.githubusercontent.com/467330/193431897-39ddd98e-a3e4-42a4-aafd-6af72abd6201.png)

### System & Environment

1. macOS latest
2. Chrome latest

**Comment by jekuer** [comment]
Just for the log (and some rubber ducking): 

- This is based on the change of how we determine whether we are dealing with a browser or not.
- Went from "new Function" before to "() => {}" now.
- Happend at multiple places, but only seems to lead to issues with the browser-check and React (but also Vue, for example).
- Therefore, it is somehow also related to the check "this===window" in combination with the mentioned adjustments.
- Accessing the navigator (which I would have considered somehow similar to "window") works at other places.
- Maybe the "this"? But replacing the arrow with a regular function does not make a difference.
- However, it needs to be the "this". Everything else would not make any sense. Maybe due to the order of loading things.
- Tested with checking for "typeof window" instead and it works that way.

Fix will come in very soon!

**Comment by houmark** [comment]
Yes, I expected that would be the issue from quickly reviewing the code. Maybe something as simple as:

`typeof window !== 'undefined'`

can work?

**Comment by jekuer** [comment]
Yes, that's the plan. Coming in any minute.

**Comment by jekuer** [comment]
Will be in v1.17

**Comment by houmark** [comment]
I can confirm this is fixed in 1.17.0 using React.

**Comment by jekuer** [comment]
@houmark , just out of interest: Is your project publicly available? Always love to see where the button lives.

**Comment by houmark** [comment]
Hey @jekuer — unfortunately not, it's behind login on a private platform.
