### ISSUE TITLE
Google calendar is not redirect to origin.

### ISSUE THREAD

**Issue by SaimumIslam** [add2cal/add-to-calendar-button#263]
The after save process is not redirect to origin (from the site you called). while outlook closes its extra tab and back to origin.

**Comment by jekuer** [comment]
This, unfortunately, is not possible.

The button opens the URL in a new tab. Therefore, when the user closes the tab, he gets back to the application. For smartphone cases, the user would need to get back to the browser manually.

There is no workaround for that, since it is up to Google, Apple, Microsoft, how they handle the user journey.
As far as I know, there is no functionality (available or planed) offered by Google to redirect the user back again.
