### ISSUE TITLE
Add possibility to track which calendar option has been selected/clicked

### ISSUE THREAD

**Issue by neilhem** [add2cal/add-to-calendar-button#276]
Nice plugin!

We need to send analytics data based on which calendar option has been selected.
I see the console log ''Event saved. Looking forward to it!' message, when we select/, click on of calendar options.

Is it possible to observe/listen for click/select events to run a custom function?

**Comment by jekuer** [comment]
At the moment, you could simply listen for the click on the respective elements. No need to add any additional functionality.
In the upcoming V2, this won't be possible any longer. We will then push events directly into the dataLayer (at least, that's the plan), assuming that most people use Google Tracking or can work with the dataLayer otherwise.
