### ISSUE TITLE
Updates in Google Calendar

### ISSUE THREAD

**Issue by syntrakristof** [add2cal/add-to-calendar-button#330]
The update works fine for Apple Calendar

Apparently for Google Calendar this also requires attendee
Are their any plans on adding attendee ? 
and also let us change PUBLISH/REQUEST ?

https://stackoverflow.com/questions/14712929/icalendar-ics-update-not-working-in-google-calendar

**Comment by jekuer** [comment]
Hi @syntrakristof ,

Did you check the example at https://add-to-calendar-button.com/en/advanced-use#5 ?

When I tried the example, it worked with Google calendar as expected. Create and cancel.
Method is automatically determined based on status and organizer. Set the organizer to force REQUEST.
However, I did not test out updates.

Setting the attendee would not make a lot of sense though - since the major case behind an Add to Calendar Button includes not knowing the attendee up front.

**Comment by jekuer** [comment]
@syntrakristof , any updates on this? Otherwise, I would close the issue for now.

**Comment by syntrakristof** [comment]
Well it is to get the update working, and this would require attendee,  request
I have been playing around with vcal format myself for quite a while and with an attendee and request and then afterwards changing it to publish the update works in Google Calendar, but not always

I know attendee is kinda 'dumb to use', but as always someone can not play nice. And for once it isn't Apple
It would be nice to get it working for updates also with Google Calendar, but like I said it isn't a major thing

**Comment by jekuer** [comment]
But the attendee needs to be the person who is adding the event, right?
Up to my knowledge, this would not work using a random attendee.

Mind that it also (in any case) requires the organizer to be set. The script will then automatically switch to "REQUEST" instead of publish. No need to make this configurable, since "REQUEST" without an organizer would not be valid and the other way around.
And for updates, it never should be "PUBLISH".

**Comment by jekuer** [comment]
@syntrakristof , please have a look at latest version 2.2.
It introduces an "attendee" option.
If you set organizer and attendee, while attendee is the person saving the event, updating works. At least with Google Cal and iCal.
