### ISSUE TITLE
[Enhancement] to buttonStyle="date"

### ISSUE THREAD

**Issue by NoralK** [add2cal/add-to-calendar-button#385]
It would be helpful to have the following enhancements for buttonStyle="date"

- add 12-hour time formatting with the ability to include am/pm
- include the timezone of event (like PDT or Pacific Daylight Time or PST or Pacific Standard Time or maybe UTC-8)
- ability to customize the icons for location and calendar
- ability to specify the different colors (background color date area, background color nondate area, font color date area, font color nondate area).  Events can be color coded and already have some of this information.
- ability to add the event organizer image/name (I know this might be difficult with the current amount of room)

Cheers

**Comment by jekuer** [comment]
@NoralK , has been built and will be part of the next minor release (most parts). However, this release unfortunately is not stable yet and will take some more weeks.

- 12-hour time will be default for English language setups
- This should be the case already (unless you are in the same timezone as the event), but will get some optimization as well
- Changing icons is not planned, since this opens up a lot of issues and security risk. What would you want to change - maybe we can make a general update?
- You can do that already to a specific extent. Have a look at the variables at https://github.com/add2cal/add-to-calendar-button/blob/main/assets/css/atcb-date.css - you can override them via the styleLight and styleDark options (see https://add-to-calendar-button.com/advanced-use#case-1).
- We skip that for the moment, since it would kill the current design a little bit and can be easily added by the host next to the button.

**Comment by NoralK** [comment]
@jekuer Thank you for getting back to me, here are my responses:

1. At this time, with the current version, it is displaying in 24-hour format when rendered.  The computer only has US-English settings
2. The events are mostly in the same TZ.  The TZ is not displayed with the event (see how I am using below).  I would like to see something like:
   `{Calendar Icon} 2023, 10:15 am - 6:30 pm PDT`
3. In other React components some have the ability to place a React component, like Fluent UI's icons or Font Awesome's icons.  And with Fluent UI I can "Bundle" an icon that changes when hovered, something like this:
```
                  <AddToCalendarButton
                    ...
/*--Would like (Names are descriptive, not want I would necessary like--*/
                    calendarIcon:={
                        event.fRecurrence === '0' ?
                           /*-these icon change when hovered-*/
                           <CalendarIcon style={{ fontSize: "2.5rem", color: event.primaryFontColor }} /> : 
                           <RecurringEventIcon style={{ fontSize: "2.5rem", color: event.primaryFontColor }} />
                    }
                    /*-this icon change when hovered-*/
                    locationIcon:={<MapPinIcon style={{ color: event.primaryFontColor }} />}
                    ...
                  />
```
4. I think you missed my point.  I understand that I could override the styles, but I need to set the values on the component.  When the calendar renders the events the events have different colors which in turn are also used in the popup and potentially this component.  Something like this:
```
                  <AddToCalendarButton
                    name="Title"
                    options="'Apple','iCal','Microsoft365','MicrosoftTeams'"
                    location="World Wide Web"
                    startDate="2023-05-11"
                    endDate="2023-05-11"
                    startTime="10:15"
                    endTime="18:30"
                    timeZone="America/Los_Angeles"
                    size="1|1|1"
                    listStyle="modal"
                    buttonStyle="date"
/*--Would like (Names are descriptive, not want I would necessary like--*/
                    backgroundColorDateArea={event.primaryBackground}
                    backgroundColorNonDateArea={event.secondaryBackground}
                    fontColorDateArea={event.primaryFontColor}
                    fontColorDateNoneArea={event.secondaryFontColor}
                  />

```
5. True, I thought of that after posting :)  And thinking more about it, the image would be too small anyways.

**Comment by jekuer** [comment]
1. correct - will be part of the next minor release 😉 
2. So, basically something like "forceTimeZoneOutput". Will need to think about this.
3. Yes, however, that's not how the script works at the moment. Mainly because it is something I would call "cross-tech-architecture".
4. As said, you can do this already - see the point "Override styles" in https://add-to-calendar-button.com/advanced-use#case-1 - otherwise I indeed have no idea what you are talking about.

You could also build your own button and make the modal appear via the atcb_action call - see https://add-to-calendar-button.com/advanced-use#case-10 - might make sense if you want to go that deep into customization 😃

**Comment by NoralK** [comment]
#3 would be the thing holding me back on using the lib
#4 If the information was a virus .... LOL

I did see this and at time I would not be interested in that.

Cheers
