### ISSUE TITLE
[Bug]: Issue with atcb overlay in containers with transform property

### ISSUE THREAD

**Issue by timotius02** [add2cal/add-to-calendar-button#419]
### What happened?

If you render the Add to calendar button in a container that has a transform, most often for incoming and/or outgoing animation, atcb-overlay will use that container as the containing block rather than the window for the basis of its fixed position, causing several issues like partial covering of the page by the background and overflow issues. This is an intended behavior for fixed positioning in CSS but cause several issues when using this library. 

### How to reproduce?

Add the add-to-calendar button in a containing div that is smaller than the page with a transform property. When the the button is opened you should see overlay only covering part of the screen. 

### Screenshots & more

https://codepen.io/timotius02/pen/qBQYJax

### System & Environment

1. Tested on Windows 11 and Ubuntu 20.04
2. Chrome
3. Latest version
4. Included with npm in a project and via cdn in the codepn

**Comment by jekuer** [comment]
@timotius02 , Thanks a lot for your feedback!

We are planning to have an option where you can force an overlay. Downside: It might then have other side effects like flowing over something like a sticky menu.
Anyhow, the best one can offer.

Until that, you could go for the modal list style, which already goes that way by design.

**Comment by jekuer** [comment]
With latest version 2.4.0, we now offer the option "forceOverlay". This would force the dropdown and also the background to be rendered above everything.
Mind that this comes with some performance drawback, since we need to keep it in sync with the original position - especially when stuff moves. Mind that this also only watches user-driven changes like scroll or resize.

Personally, for your case, I would still recommend the modal style, but up to you 😃 .
