### ISSUE TITLE
[Bug]: Outlook event from link has incorrect time

### ISSUE THREAD

**Issue by timotius02** [add2cal/add-to-calendar-button#424]
### What happened?

If you use try to create an event in outlook, the resulting event time will be the UTC time rather than the time that was inputted. This is probably a behavior on Outlook's side (Gcal converts the from UTC to the User's local time just fine) but it would be nice if this libraries creates consistency between these providers. 

### How to reproduce?

Used the button demo to create an event and follow the Outlook link. 

### Screenshots & more

[
![Screenshot (3)](https://github.com/add2cal/add-to-calendar-button/assets/5110237/e0bbb023-9ab5-4b0b-88ac-c71b42e0c41f)
![Screenshot (4)](https://github.com/add2cal/add-to-calendar-button/assets/5110237/899b2564-bda4-4560-8c47-541b74f4e999)
](url)

### System & Environment

1. Tested on Windows 11 and Ubuntu 20.04
2. Chrome
3. Latest version

**Comment by jekuer** [comment]
Hi @timotius02 ,
Thank you for your feedback. This actually is the intended behavior, since we are not able to manipulate the time zone in Outlook.
The time, however should be correct. It is only a minor UI/UX issue, right?
If the time is not correct, is your Outlook set to Jakarta time zone correctly?

**Comment by timotius02** [comment]
Yup looks like you have to set the time zone in Outlook and the dates will normalize themselves
