### ISSUE TITLE
[Bug]: location set to - "Leapfrog, Alstaviksväagen 3", independt of this setting Teams indicates that this is an online meeting, and the Location field is left empty 

### ISSUE THREAD

**Issue by SommerLeapfrog** [add2cal/add-to-calendar-button#460]
### What happened?

When selecting Teams in the dropdown, the Team booking indicate 'online meeting'. Would expect that Teams disables the button 'online meettng' and include the Location "<text>" in the location field.
When selecting Microsoft 365 the meeting location is set correctly.

### How to reproduce?

Set location to "<some text>", select Teams

### Screenshots & more

![Capture 1](https://github.com/add2cal/add-to-calendar-button/assets/144601842/8806697a-8b10-4252-b976-5712042d8a44)

### System & Environment

HP Laptop, Windows 10 Enterprise
MS Edge fo Business (Version 116.0.1938.69) 
Version: 1.4.1
Wordpress Plugin (inserted as shortcode)

**Comment by jekuer** [comment]
Hi @SommerLeapfrog,

You might have noticed that we automatically put the location into the description.
We do this, because MS Teams, unfortunately, does not support putting something the location field at the moment (see. https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#configure-deep-link-manually-to-open-a-meeting-scheduling-dialog).
Due to the same reason, we have no control over the "online meeting" option.

We will optimize things as soon as possible (supported by MS).
At the moment, there is nothing we can do, unfortunately. 😢 

All the best,
Jens

**Comment by SommerLeapfrog** [comment]
Thx for a fast response and clarification.  
Much a appreciated - and thx for a great Plug-In
