### ISSUE TITLE
[Bug]: Outlook Link Redirecting to Homepage

### ISSUE THREAD

**Issue by Azure-121** [add2cal/add-to-calendar-button#485]
### What happened?

Outlook Link Redirecting to Homepage

### How to reproduce?

This bug occurs with an account that has a subscription to MS 365. When not signed in and signing in for the first time after clicking the link, the calendar event will be made. Subsequent attempts leads to redirecting the user to the outlook homepage. 
It works when changing the link from 
"https://outlook.live.com/calendar/action/compose" to
"https://outlook.office365.com/calendar/action/compose"

### Screenshots & more

![image](https://github.com/add2cal/add-to-calendar-button/assets/77380568/80dd4819-fbc8-470f-b01d-979f37dadd62)

### System & Environment

Chrome on windows

**Comment by jekuer** [comment]
But you are referring to the outlook.com option - not the Microsoft 365 option, right?

In this case, it is no bug. This is the expected behavior.
Unfortunately, Microsoft is strictly differentiating those 2. Yes, this is extremely bad UX on Microsoft side, since the user does usually not know that he should not go to outlook.live.com if he/she has a MS 365 subscription 😵‍💫 .
