### ISSUE TITLE
[Bug]: "Calendar no longer exists" error in Google Calendar Android app

### ISSUE THREAD

**Issue by arafatamim** [add2cal/add-to-calendar-button#637]
### What happened?

Subscribing to calendar doesn't work on Android using Google Calendar option.

### How to reproduce?

Demo code from https://add-to-calendar-button.com/advanced-use#case-3
```html
<add-to-calendar-button
  name="[Test Subscription] Add to Calendar Button"
  subscribe
  icsFile="https://add2cal.github.io/ics-demo/demo-calendar.ics"
  options="'Apple','Google','iCal','Outlook.com','Microsoft 365','Microsoft Teams','Yahoo'"
  lightMode="bodyScheme"
></add-to-calendar-button>
```
1. On Android, click the Google Calendar option.
2. The Google Calendar app appears and it prompts you to select an account to add the calendar to.
3. After a brief "Processing..." message, the task fails with the error "Calendar no longer exists"

### Screenshots & more

Account selection screen:
<img src="https://github.com/user-attachments/assets/03e74826-affe-4bd3-a767-0948d376f1de" height=500 />

### System & Environment

1. Device and OS: One UI 6.1 (Android 14)
2. Browser: Chrome version 129.0.6668.81
3. Version number of the application: 2.6.21
4. Version number of Google Calendar Android app: 2024.38.0-677549254-release
5. How you include the script: Via CDN (`<script src="https://cdn.jsdelivr.net/npm/add-to-calendar-button@2.6.21" async defer></script>`)

**Comment by jekuer** [comment]
Hi @arafatamim ,
It seems that the Google Calendar App is currently no longer supporting to subscribe to external calendars.
Since, at the same time, they are stronger enforcing a redirect from the browser to the app, I do not see an option to mitigate this. The only valid solution is using our PRO version, as this is placing a middleware in the process, where we at least can catch the user and guide him.
I hope that Google either resolves the issue or comes up with some new scheme we can use.
Closing this here, but opening a discussion to keep an eye on it.
